---
- name: Install nginx
  ansible.builtin.apt:
    pkg:
     - nginx
    state: present
    update_cache: true

- name: Remove default Nginx config file
  ansible.builtin.file:
    path: "{{ nginx_sites_enabled_dir }}/default"
    state: absent

- name: Upload Nginx config file
  ansible.builtin.template:
    src: nginx.j2
    dest: "{{ nginx_sites_available_dir }}/{{ nginx_conf_file }}"

- name: Create a symbolic link
  ansible.builtin.file:
    src: "{{ nginx_sites_available_dir }}/{{ nginx_conf_file }}"
    dest: "{{ nginx_sites_enabled_dir }}/{{ nginx_conf_file }}"
    state: link
  notify: Restart nginx