---
- name: Install pyenv dependencies
  ansible.builtin.apt:
    pkg:
     - make
     - build-essential
     - libssl-dev
     - zlib1g-dev
     - libbz2-dev
     - libreadline-dev
     - libsqlite3-dev
     - wget
     - curl
     - llvm
     - libncursesw5-dev
     - xz-utils
     - tk-dev
     - libxml2-dev
     - libxmlsec1-dev
     - libffi-dev
     - liblzma-dev
     - python3-venv
     - gcc-10
    state: present
    update_cache: true

- name: Download pyenv script
  ansible.builtin.get_url:
    dest: /tmp/pyenv.sh
    url: https://pyenv.run
    mode: "0555"

- name: Execute pyenv install script
  ansible.builtin.shell:
    cmd: /tmp/pyenv.sh
    creates: "{{ ansible_env.HOME }}/.pyenv"

- name: Install required python version
  ansible.builtin.command:
    cmd: "pyenv install {{ python_version }}"
    creates: "{{ ansible_env.HOME }}/.pyenv/versions/{{ python_version }}"
  environment:
    PATH: "{{ ansible_env.HOME }}/.pyenv/bin:{{ ansible_env.PATH }}"
    CC: "gcc-10"

- name: Install pyenv virtualenv dependencies
  ansible.builtin.apt:
    pkg:
    - libmysqlclient-dev
    - python3-dev
    - python3-pip
    state: present
    update_cache: true

- name: Clone venv repo
  ansible.builtin.git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: "{{ ansible_env.HOME }}/plugins/pyenv-virtualenv"
