---
- name: Deploy nodejs 
  hosts: aws_ec2
  gather_facts: false
  become: true
  roles:
   - node
   - nginx
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: sujata-static-website-one
    ansible_aws_ssm_profile: default