---
- name: Deploy nginx in public server
  hosts: public_server
  gather_facts: true
  roles:
   - nginx
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: sujata-static-website-one
    ansible_aws_ssm_profile: default
    ansible_become: true
    ansible_become_user: root